=== StefaPP/XML2016Projekat/XMLProject/src/schema/akt.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    targetNamespace="http://www.parlament.gov.rs/propisi"
    xmlns:p="http://www.parlament.gov.rs/propisi"
    finalDefault="#all" xmlns="http://www.w3.org/ns/rdfa#"
    xmlns:pred="http://www.parlament.gov.rs/propisi/predicate/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <xs:element name="Akt">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="p:Glavni_deo"/>
                <xs:element ref="p:Sporedni_deo"/>
            </xs:sequence>
            <xs:attribute name="status" type="xs:string"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glavni_deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Odeljak"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Clan"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Stav"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Tacka"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Podtacka"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Alineja"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Glava"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:Deo"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="Sporedni_deo">
        <xs:complexType>
            <xs:choice>
                <xs:element name="Akt_u_proceduri">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Predlagac" type="xs:string"/>
                            <xs:element name="Upucuje_se" type="xs:string"/>
                            <xs:element name="Meta_podaci">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element ref="p:Oznaka"/>
                                        <xs:element ref="p:Mesto"/>
                                        <xs:element ref="p:Datum"/>
                                        <xs:element ref="p:Vrsta"/>
                                        <xs:element ref="p:Naziv"/>
                                        <xs:element ref="p:BrUkupnihGlasova"/>
                                        <xs:element ref="p:BrPozitivnihGlasova"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Donet_akt">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Donet_od_strane" type="xs:string"/>
                            <xs:element name="Po_postupku" type="xs:string"/>
                            <xs:element name="Po_cilju" type="xs:string"/>
                            <xs:element name="Meta_podaci">
                                <xs:complexType>
                                    <xs:all>
                                        <xs:element ref="p:Oznaka"/>
                                        <xs:element ref="p:Datum"/>
                                        <xs:element ref="p:Vrsta"/>
                                        <xs:element ref="p:Naziv"/>
                                    </xs:all>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="Osnov_donosenja" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
            <xs:attribute name="about"/>
            <xs:anyAttribute/>
        </xs:complexType>
    </xs:element>
    <xs:complexType mixed="true" name="SadrzajTacke">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
            <xs:element name="Podtacka">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajPodtacke"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajStav">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Tacka">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajTacke"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajClan">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Tacka">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajTacke"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="Stav">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajStav"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajOdeljka">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Clan">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajClan"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajPodtacke">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Alineja">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="xs:string"/>
                        <xs:element name="Status">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="status_izmene" type="xs:string"/>
                                    <xs:element name="ref">
                                        <xs:complexType>
                                            <xs:simpleContent>
                                                <xs:extension base="xs:string">
                                                  <xs:attribute name="id_ref" type="xs:string"/>
                                                </xs:extension>
                                            </xs:simpleContent>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajGlave">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Clan">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajClan"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Odeljak">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajOdeljka"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType mixed="true" name="SadrzajDeo">
        <xs:sequence maxOccurs="unbounded" minOccurs="0">
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Clan">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajClan"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Odeljak">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajOdeljka"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" name="Glava">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Sadrzaj" type="p:SadrzajGlave"/>
                    </xs:sequence>
                    <xs:attribute name="oznaka" type="xs:string"/>
                    <xs:attribute name="naziv" type="xs:string"/>
                    <xs:attribute name="opis" type="xs:string"/>
                    <xs:anyAttribute namespace="##any"/>
                </xs:complexType>
            </xs:element>
            <xs:element maxOccurs="unbounded" minOccurs="0" ref="p:ref"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="Naziv">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TStatusAmandmana">
        <xs:restriction base="xs:string">
            <xs:enumeration value="odbijen"/>
            <xs:enumeration value="prihvacen"/>
            <xs:enumeration value="u_proceduri"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element default="0" name="BrPozitivnihGlasova">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:int">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element default="0" name="BrUkupnihGlasova">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:int">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Oznaka">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Mesto">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Datum">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:date">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="Vrsta">
        <xs:complexType>
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:element name="ref">
        <xs:complexType mixed="false">
            <xs:simpleContent>
                <xs:extension base="xs:string">
                    <xs:attribute name="id_ref">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:pattern value="(\/[A-Za-z]*[0-9]*)+"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:anyAttribute namespace="##any" processContents="lax"/>
                </xs:extension>
            </xs:simpleContent>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="TStatusAkta">
        <xs:restriction base="xs:string">
            <xs:enumeration value="donet"/>
            <xs:enumeration value="u_proceduri"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:element name="status_izmene" type="p:TStatusAkta"/>
    <xs:complexType name="AmandmanStatus">
        <xs:all>
            <xs:element ref="p:ref"/>
            <xs:element ref="p:status_izmene"/>
        </xs:all>
    </xs:complexType>
    <xs:element name="status" type="p:AmandmanStatus"/>
    <xs:element name="Odeljak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajOdeljka"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Clan">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajClan"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Stav">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajStav"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Tacka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajTacke"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Podtacka">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajPodtacke"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Alineja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="xs:string"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Glava">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajGlave"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="Deo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Sadrzaj" type="p:SadrzajDeo"/>
                <xs:element ref="p:status"/>
            </xs:sequence>
            <xs:attribute name="oznaka" type="xs:string"/>
            <xs:attribute name="naziv" type="xs:string"/>
            <xs:attribute name="opis" type="xs:string"/>
            <xs:anyAttribute namespace="##any"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== StefaPP/XML2016Projekat/XMLProject/src/xml/akti/Akt6-u_proceduri.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt 
xmlns:p="http://www.parlament.gov.rs/propisi"
xmlns="http://www.w3.org/ns/rdfa#"
xmlns:pred="http://www.parlament.gov.rs/propisi/predicate/"  
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.parlament.gov.rs/propisi ../../schema/akt.xsd ">
  <p:Glavni_deo/>
<p:Sporedni_deo about="http://www.parlament.gov.rs/propisi/akti/u_proceduri/doc6">
    <p:Akt_u_proceduri>
      <p:Predlagac>p:Predlagac</p:Predlagac>
      <p:Upucuje_se>p:Upucuje_se</p:Upucuje_se>
      <p:Meta_podaci>
        <p:Oznaka property="pred:oznaka" datatype="xs:string">doc6</p:Oznaka>
        <p:Mesto property="pred:mesto" datatype="xs:string">Beograd</p:Mesto>
        <p:Datum property="pred:datum" datatype="xs:date">2013-08-05</p:Datum>
        <p:Vrsta property="pred:vrsta" datatype="xs:string">Odluka</p:Vrsta>
        <p:Naziv property="pred:naziv" datatype="xs:string">Akt o kaznjavanju koljaca koji ne placaju obrezivanje</p:Naziv>
        <p:BrUkupnihGlasova>0</p:BrUkupnihGlasova>
        <p:BrPozitivnihGlasova>0</p:BrPozitivnihGlasova>
      </p:Meta_podaci>
    </p:Akt_u_proceduri>
  </p:Sporedni_deo>
</p:Akt>

=== StefaPP/XML2016Projekat/XMLProject/src/xml/akti/Akt4-donet.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt xmlns:p="http://www.parlament.gov.rs/propisi" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.parlament.gov.rs/propisi ../../schema/akt.xsd ">
  <p:Glavni_deo/>
<p:Sporedni_deo about="http://www.parlament.gov.rs/propisi/akti/doneti/doc4">
    <p:Donet_akt>
      <p:Donet_od_strane>p:Predlagac</p:Donet_od_strane>
      <p:Po_postupku>p:Upucuje_se</p:Po_postupku>
      <p:Po_cilju>p:bla</p:Po_cilju>
      <p:Meta_podaci>
       		<p:Oznaka property="pred:oznaka" datatype="xs:string">doc4</p:Oznaka>
        	<p:Datum property="pred:datum" datatype="xs:date">2012-01-03</p:Datum>
        	<p:Vrsta property="pred:vrsta" datatype="xs:string">Odluka</p:Vrsta>
        	<p:Naziv property="pred:naziv" datatype="xs:string">Odluka o penzionisanju Prcmilojke</p:Naziv>
      	</p:Meta_podaci>
      	<p:Osnov_donosenja>dsa</p:Osnov_donosenja>
    </p:Donet_akt>
  </p:Sporedni_deo>
</p:Akt>

=== StefaPP/XML2016Projekat/XMLProject/src/xml/akti/Prcmilojka.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Akt xmlns:p="http://www.parlament.gov.rs/propisi" 
xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns="http://www.w3.org/ns/rdfa#"
xmlns:pred="http://www.parlament.gov.rs/propisi/predicate/" 
xsi:schemaLocation="http://www.parlament.gov.rs/propisi ../../schema/akt.xsd ">

  <p:Glavni_deo/>
<p:Sporedni_deo about="http://www.parlament.gov.rs/propisi/akti/doneti/doc3">
    <p:Akt_u_proceduri>
      <p:Predlagac>p:Predlagac</p:Predlagac>
      <p:Upucuje_se>p:Upucuje_se</p:Upucuje_se>
      <p:Meta_podaci>
        <p:Oznaka property="pred:oznaka" datatype="xs:string">doc1</p:Oznaka>
        <p:Mesto property="pred:mesto" datatype="xs:string">Beograd</p:Mesto>
        <p:Datum property="pred:datum" datatype="xs:date">2016-07-01</p:Datum>
        <p:Vrsta property="pred:vrsta" datatype="xs:string">Zakon</p:Vrsta>
        <p:Naziv property="pred:naziv" datatype="xs:string">ja dono akt</p:Naziv>
        <p:BrUkupnihGlasova>0</p:BrUkupnihGlasova>
        <p:BrPozitivnihGlasova>0</p:BrPozitivnihGlasova>
      </p:Meta_podaci>
    </p:Akt_u_proceduri>
  </p:Sporedni_deo>
</p:Akt>
